"use strict";


module.exports = {
  TYPE_TOPIC: 5,
  TYPE_STANDARD: 10,
  TYPE_REOMMEND: 11,
  TYPE_EXPLORE: 19,
  TYPE_EXPLORE_DEFINE: 20,
  TYPE_EXPLORE_INSTANCE: 21,
  TYPE_CREATE_DEFINE:10000
}
